#!/usr/bin/env bash
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

bash "$ROOT/scripts/modules/lan/plan.sh"

# Disable conflicting cloud-init netplan if present (common on cloud images)
if [[ -d /etc/netplan ]]; then
  for f in /etc/netplan/*; do
    [[ -f "$f" ]] || continue
    base="$(basename "$f")"
    [[ "$base" == 50-ubrouter.yaml ]] && continue
    # Keep but make optional conflicts less likely: leave other files; our 50- has higher priority numbers... 
    # Actually lower number = earlier. 50 is mid. Disable 00-installer / 50-cloud-init by renaming.
    case "$base" in
      00-installer-config.yaml|50-cloud-init.yaml|01-netcfg.yaml)
        info "disable conflicting netplan: $base"
        mv -f "$f" "${f}.ubrouter-disabled" || true
        ;;
    esac
  done
fi

bash "$ROOT/scripts/lib/render-netplan.sh" /etc/netplan/50-ubrouter.yaml

info "lan: netplan generate + apply"
netplan generate
netplan apply || {
  warn "netplan apply вернул ошибку — проверьте конфиг; reboot может понадобиться после rename"
}

naming="$(ans_get interfaces.naming)"
if [[ "$naming" != "keep" && -n "$naming" ]]; then
  info "lan: udevadm trigger после set-name (naming=$naming)"
  udevadm control --reload 2>/dev/null || true
  udevadm trigger --action=add 2>/dev/null || true
  udevadm settle --timeout=15 2>/dev/null || true
  sleep 2
  # verify expected names exist
  map_json="$(ans_get_json interfaces.map)"
  missing="$(python3 -c '
import json,sys,subprocess
m=json.loads(sys.argv[1] or "[]") or []
miss=[]
for e in m:
  n=e.get("name")
  if not n: continue
  r=subprocess.run(["ip","link","show","dev",n], capture_output=True)
  if r.returncode!=0: miss.append(n)
print(" ".join(miss))
' "$map_json")"
  if [[ -n "$missing" ]]; then
    warn "lan: имена ещё не видны: $missing — нужен reboot, затем проверка ip link"
  fi
fi

# Give networkd a moment
sleep 2
systemctl try-restart systemd-networkd 2>/dev/null || true
sleep 1

lan_if="$(ans_get lan.interface)"
if ans_true interfaces.bridge.enabled; then
  lan_if="$(ans_get interfaces.bridge.name)"
  [[ -n "$lan_if" ]] || lan_if=br-lan
fi

if ip -4 addr show dev "$lan_if" 2>/dev/null | grep -q 'inet '; then
  info "lan: apply OK: $lan_if has IPv4"
else
  warn "lan: нет IPv4 на $lan_if пока — проверьте кабель/rename/reboot"
fi

# --- IPv6 RA (radvd) when lan.ipv6.enabled ---
lan_v6_en=false
ans_true lan.ipv6.enabled && lan_v6_en=true
ra_val="$(ans_get lan.ipv6.ra 2>/dev/null || echo true)"
[[ -z "$ra_val" || "$ra_val" == "null" ]] && ra_val=true
ra_want=true
[[ "$ra_val" == "false" || "$ra_val" == "0" || "$ra_val" == "no" ]] && ra_want=false
lan_v6_addr="$(ans_get lan.ipv6.address 2>/dev/null || true)"

if [[ "$lan_v6_en" == "true" && "$ra_want" == "true" && -n "$lan_v6_addr" && "$lan_v6_addr" != "null" ]]; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y -qq radvd >/dev/null || warn "radvd install failed"
  # host addr fd00::1/64 → advertise prefix fd00::/64
  prefix="$(python3 - "$lan_v6_addr" <<'PY'
import ipaddress, sys
s = sys.argv[1]
try:
    iface = ipaddress.IPv6Interface(s)
    print(f"{iface.network.network_address}/{iface.network.prefixlen}")
except Exception:
    print(s)
PY
)"
  cat >/etc/radvd.conf <<EOF
# Generated by UBrouter
interface $lan_if
{
  AdvSendAdvert on;
  MinRtrAdvInterval 30;
  MaxRtrAdvInterval 100;
  prefix $prefix
  {
    AdvOnLink on;
    AdvAutonomous on;
    AdvRouterAddr on;
  };
};
EOF
  chmod 0644 /etc/radvd.conf
  systemctl enable radvd 2>/dev/null || true
  systemctl restart radvd || warn "radvd restart failed — проверьте prefix $prefix"
  info "lan: radvd RA on $lan_if prefix=$prefix"
else
  if systemctl list-unit-files radvd.service >/dev/null 2>&1; then
    if [[ -f /etc/radvd.conf ]] && grep -q 'Generated by UBrouter' /etc/radvd.conf 2>/dev/null; then
      systemctl disable --now radvd 2>/dev/null || true
      mv -f /etc/radvd.conf /etc/radvd.conf.ubrouter-disabled 2>/dev/null || true
      info "lan: radvd cleanup (IPv6 RA off)"
    fi
  fi
fi
