!/usr/bin/env bash
# Apply IPsec (strongSwan transport + PSK) for GRE/EOIP/IPIP tunnels
# when vpn.clients[].ipsec is true / psk / transport.
#
# PSK: /etc/ubrouter/answers.local.yaml → vpn.tunnel_psks.<name>
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"
clients_json="[]"
[[ -f "$WORKDIR/vpn/clients.json" ]] && clients_json="$(cat "$WORKDIR/vpn/clients.json")"
[[ "$clients_json" == "[]" ]] && clients_json="$(ans_get_json vpn.clients)"

# Quick check: any tunnel wants ipsec?
need=0
if python3 - "$clients_json" <<'PY'
import json, sys
clients = json.loads(sys.argv[1] or "[]") or []
def wants(c):
    v = c.get("ipsec")
    if v in (True, "true", "1", "yes", "psk", "transport"):
        return True
    if isinstance(v, dict) and v.get("enabled"):
        return True
    return False
for c in clients:
    if (c.get("type") or "").lower() in ("gre", "eoip", "ipip") and wants(c):
        raise SystemExit(0)
raise SystemExit(1)
PY
then
  need=1
fi

# Remove stale snippets when none need ipsec
if [[ "$need" -eq 0 ]]; then
  rm -f /etc/swanctl/conf.d/ubrouter-tunnel-ipsec-*.conf 2>/dev/null || true
  if [[ -S /run/charon.vici ]]; then
    swanctl --load-all --noprompt 2>/dev/null || true
  fi
  info "tunnel-ipsec: нет gre/eoip/ipip с ipsec — cleaned"
  exit 0
fi

export DEBIAN_FRONTEND=noninteractive
apt-get install -y -qq strongswan strongswan-swanctl libcharon-extra-plugins >/dev/null

ensure_dir /etc/swanctl/conf.d
if [[ ! -f /etc/swanctl/swanctl.conf ]] || ! grep -q 'include conf.d' /etc/swanctl/swanctl.conf 2>/dev/null; then
  echo 'include conf.d/*.conf' >/etc/swanctl/swanctl.conf
  chmod 0640 /etc/swanctl/swanctl.conf
fi

python3 - "$clients_json" <<'PY'
import json, subprocess, sys
from pathlib import Path

clients = json.loads(sys.argv[1] or "[]") or []

def load_yaml(path):
    p = Path(path)
    if not p.is_file():
        return {}
    import yaml
    return yaml.safe_load(p.read_text(encoding="utf-8")) or {}

local = load_yaml("/etc/ubrouter/answers.local.yaml")
tunnel_psks = ((local.get("vpn") or {}).get("tunnel_psks")) or {}

def wants_ipsec(c):
    v = c.get("ipsec")
    if v in (True, "true", "1", "yes", "psk", "transport"):
        return True
    if isinstance(v, dict) and v.get("enabled"):
        return True
    return False

# wipe previous tunnel-ipsec snippets
for old in Path("/etc/swanctl/conf.d").glob("ubrouter-tunnel-ipsec-*.conf"):
    old.unlink(missing_ok=True)

wrote = 0
for c in clients:
    if (c.get("type") or "").lower() not in ("gre", "eoip", "ipip"):
        continue
    if not wants_ipsec(c):
        continue
    name = c.get("name") or c.get("type") or "tun"
    remote = c.get("remote")
    if not remote:
        print(f"WARN: tunnel-ipsec {name}: нет remote — skip", file=sys.stderr)
        continue
    typ = (c.get("type") or "gre").lower()
    ipsec = c.get("ipsec")
    psk = None
    if isinstance(ipsec, dict):
        psk = ipsec.get("psk") or ipsec.get("secret")
    psk = psk or c.get("ipsec_psk") or tunnel_psks.get(name)
    if not psk:
        print(
            f"WARN: tunnel-ipsec {name}: нет PSK — vpn.tunnel_psks.{name} в answers.local.yaml",
            file=sys.stderr,
        )
        continue

    secret = json.dumps(str(psk))
    conf = f"""# Generated by UBrouter — IPsec transport for {typ}/{name}
connections {{
  ubrouter_{name}_ipsec {{
    version = 2
    proposals = aes256-sha256-modp2048,aes256-sha256-ecp256,aes128-sha256-modp2048
    remote_addrs = {remote}
    local {{
      auth = psk
    }}
    remote {{
      auth = psk
      id = {remote}
    }}
    children {{
      {name}_{typ} {{
        mode = transport
        start_action = start
        dpd_action = restart
        esp_proposals = aes256gcm16-aes128gcm16,aes256-sha256,aes128-sha256
      }}
    }}
  }}
}}

secrets {{
  ike-ubrouter-{name} {{
    id = {remote}
    secret = {secret}
  }}
}}
"""
    out = Path(f"/etc/swanctl/conf.d/ubrouter-tunnel-ipsec-{name}.conf")
    out.write_text(conf, encoding="utf-8")
    out.chmod(0o600)
    print(f"--> tunnel-ipsec: {typ}/{name} remote={remote} transport+PSK")
    wrote += 1

if wrote == 0:
    raise SystemExit(0)

for unit in ("strongswan-starter", "strongswan"):
    subprocess.call(["systemctl", "enable", unit], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    subprocess.call(["systemctl", "restart", unit], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

subprocess.call(["swanctl", "--load-all", "--noprompt"])
print(f"--> tunnel-ipsec: {wrote} SA(s); swanctl --list-sas / --list-conns")
PY

info "tunnel-ipsec: done"
