#!/usr/bin/env bash
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

if ! ans_true services.chrony; then
  info "ntp: skip — cleanup chrony"
  systemctl disable --now chrony 2>/dev/null || systemctl disable --now chronyd 2>/dev/null || true
  if [[ -f /etc/chrony/chrony.conf ]] && grep -q 'Generated by UBrouter\|UBrouter' /etc/chrony/chrony.conf 2>/dev/null; then
    mv -f /etc/chrony/chrony.conf /etc/chrony/chrony.conf.ubrouter-disabled 2>/dev/null || true
  fi
  # restore timesyncd only if we masked it
  if systemctl is-enabled systemd-timesyncd 2>/dev/null | grep -q masked; then
    systemctl unmask systemd-timesyncd 2>/dev/null || true
  fi
  exit 0
fi

bash "$ROOT/scripts/modules/ntp/plan.sh"
WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"
install -m 0644 "$WORKDIR/ntp/chrony.conf" /etc/chrony/chrony.conf

# Avoid fight with systemd-timesyncd
systemctl disable --now systemd-timesyncd 2>/dev/null || true
systemctl mask systemd-timesyncd 2>/dev/null || true

systemctl enable chrony >/dev/null 2>&1 || systemctl enable chronyd >/dev/null 2>&1 || true
systemctl restart chrony 2>/dev/null || systemctl restart chronyd 2>/dev/null || true
info "ntp: apply OK"
