#!/usr/bin/env bash
# Module: ntp — chrony
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

if ! ans_true services.chrony; then
  info "ntp: services.chrony=false — skip"
  exit 0
fi

lan_cidr="$(ans_get lan.cidr)"
# allow LAN subnet /24 guess
net="$(lan_network_guess "$lan_cidr")"

WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"
ensure_dir "$WORKDIR/ntp"
cat >"$WORKDIR/ntp/chrony.conf" <<EOF
# Generated by UBrouter
confdir /etc/chrony/conf.d
sourcedir /run/chrony-dhcp
sourcedir /etc/chrony/sources.d
keyfile /etc/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
ntsdumpdir /var/lib/chrony
leapsectz right/UTC
logdir /var/log/chrony
maxupdateskew 100.0
rtcsync
makestep 1 3

allow ${net}
local stratum 10

pool ntp.ubuntu.com        iburst maxsources 4
pool 0.pool.ntp.org        iburst maxsources 2
EOF
info "ntp: plan OK allow $net"
