!/usr/bin/env bash
# WireGuard clients + servers from answers vpn.*
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/vpn-cleanup.sh"
ans_require
need_root

WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"
clients_json="[]"
servers_json="[]"
[[ -f "$WORKDIR/vpn/clients.json" ]] && clients_json="$(cat "$WORKDIR/vpn/clients.json")"
[[ -f "$WORKDIR/vpn/servers.json" ]] && servers_json="$(cat "$WORKDIR/vpn/servers.json")"

if [[ "$clients_json" == "[]" && "$servers_json" == "[]" ]]; then
  clients_json="$(ans_get_json vpn.clients)"
  servers_json="$(ans_get_json vpn.servers)"
fi

ensure_dir /etc/wireguard
chmod 0700 /etc/wireguard
ensure_dir /var/lib/ubrouter/vpn

python3 - "$clients_json" "$servers_json" <<'PY'
import json, os, shutil, subprocess, sys
from pathlib import Path

clients = [c for c in (json.loads(sys.argv[1] or "[]") or []) if c.get("type") == "wireguard"]
servers = [s for s in (json.loads(sys.argv[2] or "[]") or []) if s.get("type") == "wireguard"]
state = Path("/var/lib/ubrouter/vpn/managed-wireguard.list")
prev = state.read_text(encoding="utf-8").split() if state.is_file() else []

desired = []
for c in clients:
    desired.append(c.get("name") or "wg0")
for s in servers:
    desired.append(s.get("name") or "wg-server")
desired = [n for n in desired if n]
keep = set(desired)

def disable_iface(name: str):
    subprocess.call(
        ["systemctl", "disable", "--now", f"wg-quick@{name}"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    conf = Path(f"/etc/wireguard/{name}.conf")
    if conf.is_file():
        # only archive if we managed it (in prev or Generated marker)
        text = conf.read_text(encoding="utf-8", errors="ignore")
        if name in prev or "SaveConfig = false" in text or "Generated by UBrouter" in text:
            conf.rename(str(conf) + ".ubrouter-disabled")

for name in prev:
    if name and name not in keep:
        print(f"--> wireguard: remove orphan {name}")
        disable_iface(name)

def enable_unit(name: str):
    subprocess.check_call(["systemctl", "enable", f"wg-quick@{name}"])
    subprocess.call(["systemctl", "restart", f"wg-quick@{name}"])

for c in clients:
    name = c.get("name") or "wg0"
    cfg = c.get("config_file")
    dst = Path(f"/etc/wireguard/{name}.conf")
    if cfg and Path(cfg).is_file():
        shutil.copy2(cfg, dst)
        text = dst.read_text(encoding="utf-8", errors="ignore")
        if "Generated by UBrouter" not in text:
            dst.write_text("# Generated by UBrouter (client)\n" + text, encoding="utf-8")
        dst.chmod(0o600)
        print(f"--> wireguard: client {name} from {cfg}")
        enable_unit(name)
    else:
        print(f"WARN: wireguard client {name}: нет config_file — skip", file=sys.stderr)

for s in servers:
    name = s.get("name") or "wg-server"
    dst = Path(f"/etc/wireguard/{name}.conf")
    listen = int(s.get("listen") or 51820)
    address = s.get("address") or "10.66.0.1/24"
    priv = Path(f"/etc/wireguard/{name}.key")
    if not priv.is_file():
        priv.write_text(subprocess.check_output(["wg", "genkey"], text=True).strip() + "\n")
        priv.chmod(0o600)
    private = priv.read_text().strip()
    public = subprocess.check_output(["wg", "pubkey"], input=private + "\n", text=True).strip()
    Path(f"/etc/wireguard/{name}.pub").write_text(public + "\n")
    peers = s.get("peers") or []
    lines = [
        "# Generated by UBrouter",
        "[Interface]",
        f"Address = {address}",
        f"ListenPort = {listen}",
        f"PrivateKey = {private}",
        "SaveConfig = false",
        "",
    ]
    for p in peers:
        lines += [
            "[Peer]",
            f"PublicKey = {p.get('public_key', '')}",
            f"AllowedIPs = {p.get('allowed_ips', '0.0.0.0/0')}",
        ]
        if p.get("endpoint"):
            lines.append(f"Endpoint = {p['endpoint']}")
        if p.get("preshared_key"):
            lines.append(f"PresharedKey = {p['preshared_key']}")
        lines.append("")
    dst.write_text("\n".join(lines), encoding="utf-8")
    dst.chmod(0o600)
    print(f"--> wireguard: server {name} listen {listen} pubkey={public}")
    enable_unit(name)

state.write_text("\n".join(desired) + ("\n" if desired else ""), encoding="utf-8")
if not clients and not servers:
    print("--> wireguard: cleanup done (nothing in answers)")
PY

# Open firewall UDP for WG servers (best-effort; nat-firewall owns full policy)
servers_json="$(ans_get_json vpn.servers)"
python3 - "$servers_json" <<'PY' || true
import json, subprocess, sys
servers = [s for s in (json.loads(sys.argv[1] or "[]") or []) if s.get("type") == "wireguard"]
for s in servers:
    port = int(s.get("listen") or 51820)
    subprocess.call(
        f'nft list table inet filter >/dev/null 2>&1 && '
        f'nft add rule inet filter input udp dport {port} accept 2>/dev/null || true',
        shell=True,
    )
PY

info "wireguard: done"
