#!/usr/bin/env bash
# Module: monitoring — netwatch + VPN Telegram notify (IKEv2/GRE/EOIP/WG/OVPN)
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

nw_en="$(ans_get monitoring.netwatch.enabled 2>/dev/null || true)"
vpn_en="$(ans_get monitoring.vpn_notify.enabled 2>/dev/null || true)"
nw_on=0 vpn_on=0
[[ "$nw_en" == "true" || "$nw_en" == "1" || "$nw_en" == "yes" ]] && nw_on=1
[[ "$vpn_en" == "true" || "$vpn_en" == "1" || "$vpn_en" == "yes" ]] && vpn_on=1

if [[ "$nw_on" -eq 0 && "$vpn_on" -eq 0 ]]; then
  info "monitoring: netwatch/vpn_notify выключены — skip"
  systemctl disable --now ubrouter-netwatch.timer 2>/dev/null || true
  systemctl disable --now ubrouter-vpn-watch.timer 2>/dev/null || true
  exit 0
fi

ensure_dir /etc/ubrouter 0750
ensure_dir /var/lib/ubrouter/netwatch
ensure_dir /var/lib/ubrouter/vpn-notify
ensure_dir /usr/local/lib/ubrouter

host_label="$(ans_get monitoring.netwatch.host_label 2>/dev/null || true)"
[[ -n "$host_label" ]] || host_label="$(ans_get host.hostname 2>/dev/null || echo ubrouter)"
tg_nw="$(ans_get monitoring.netwatch.telegram 2>/dev/null || echo false)"
tg_vpn="$(ans_get monitoring.vpn_notify.telegram 2>/dev/null || echo true)"
tg_en=0
[[ "$tg_nw" == "true" || "$tg_nw" == "1" || "$tg_nw" == "yes" ]] && tg_en=1
[[ "$vpn_on" -eq 1 && ( "$tg_vpn" == "true" || "$tg_vpn" == "1" || "$tg_vpn" == "yes" ) ]] && tg_en=1

# secrets from answers.local
token=""; chat=""
if [[ -f /etc/ubrouter/answers.local.yaml ]]; then
  eval "$(python3 - <<'PY'
import yaml
from pathlib import Path
p = Path("/etc/ubrouter/answers.local.yaml")
try:
    d = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
except Exception:
    d = {}
mon = d.get("monitoring") or {}
tg = mon.get("telegram") or {}
token = tg.get("bot_token") or mon.get("telegram_bot_token") or ""
chat = tg.get("chat_id") or mon.get("telegram_chat_id") or ""
def esc(s):
    return str(s).replace("'", "'\"'\"'")
print(f"token='{esc(token)}'")
print(f"chat='{esc(chat)}'")
PY
)"
fi

ping_count="$(ans_get monitoring.netwatch.ping_count 2>/dev/null || echo 2)"
ping_to="$(ans_get monitoring.netwatch.ping_timeout_sec 2>/dev/null || echo 1)"
[[ -n "$ping_count" ]] || ping_count=2
[[ -n "$ping_to" ]] || ping_to=1

if [[ ! -f /etc/ubrouter/netwatch.env ]]; then
  cat >/etc/ubrouter/netwatch.env <<EOF
# UBrouter telegram / netwatch — chmod 0600
TELEGRAM_ENABLED=$tg_en
TELEGRAM_BOT_TOKEN=${token:-CHANGE_ME}
TELEGRAM_CHAT_ID=${chat:-}
HOST_LABEL=$host_label
PING_COUNT=$ping_count
PING_TIMEOUT_SEC=$ping_to
EOF
else
  python3 - "$tg_en" "$host_label" "$ping_count" "$ping_to" "$token" "$chat" <<'PY'
import sys
from pathlib import Path
tg_en, host_label, ping_count, ping_to, token, chat = sys.argv[1:]
path = Path("/etc/ubrouter/netwatch.env")
data = {}
for line in path.read_text(encoding="utf-8").splitlines():
    if "=" in line and not line.strip().startswith("#"):
        k, v = line.split("=", 1)
        data[k.strip()] = v.strip().strip('"').strip("'")
data["TELEGRAM_ENABLED"] = tg_en
data["HOST_LABEL"] = host_label
data["PING_COUNT"] = ping_count
data["PING_TIMEOUT_SEC"] = ping_to
if token and token != "CHANGE_ME":
    data["TELEGRAM_BOT_TOKEN"] = token
if chat:
    data["TELEGRAM_CHAT_ID"] = chat
data.setdefault("TELEGRAM_BOT_TOKEN", "CHANGE_ME")
data.setdefault("TELEGRAM_CHAT_ID", "")
lines = [
    "# UBrouter telegram / netwatch — chmod 0600",
    f"TELEGRAM_ENABLED={data['TELEGRAM_ENABLED']}",
    f"TELEGRAM_BOT_TOKEN={data['TELEGRAM_BOT_TOKEN']}",
    f"TELEGRAM_CHAT_ID={data['TELEGRAM_CHAT_ID']}",
    f"HOST_LABEL={data['HOST_LABEL']}",
    f"PING_COUNT={data['PING_COUNT']}",
    f"PING_TIMEOUT_SEC={data['PING_TIMEOUT_SEC']}",
]
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY
fi
chmod 0600 /etc/ubrouter/netwatch.env

install -m 0755 "$ROOT/scripts/lib/telegram-send.sh" /usr/local/sbin/ubrouter-telegram-send.sh
install -m 0755 "$ROOT/scripts/modules/monitoring/vpn-updown-ikev2.sh" /usr/local/sbin/ubrouter-vpn-updown-ikev2.sh
install -m 0755 "$ROOT/scripts/modules/monitoring/vpn-watch.sh" /usr/local/sbin/ubrouter-vpn-watch.sh

# --- netwatch ---
if [[ "$nw_on" -eq 1 ]]; then
  hosts_json="$(ans_get_json monitoring.netwatch.hosts 2>/dev/null || echo '[]')"
  interval="$(ans_get monitoring.netwatch.interval_sec 2>/dev/null || echo 10)"
  [[ -n "$interval" ]] || interval=10
  python3 - "$hosts_json" <<'PY' >/etc/ubrouter/netwatch-hosts.conf
import json, sys
hosts = json.loads(sys.argv[1] or "[]") or []
print("# Generated by UBrouter monitoring/netwatch")
print("# Format: enabled|host|label|message_down|message_up")
print()
if not hosts:
    print("yes|1.1.1.1|Internet|Internet is down|Internet is up")
else:
    for h in hosts:
        en = "yes" if h.get("enabled", True) else "no"
        host = h.get("host") or ""
        if not host:
            continue
        label = h.get("label") or host
        md = h.get("msg_down") or f"{label} is down"
        mu = h.get("msg_up") or f"{label} is up"
        print(f"{en}|{host}|{label}|{md}|{mu}")
PY
  chmod 0644 /etc/ubrouter/netwatch-hosts.conf
  install -m 0755 "$ROOT/scripts/modules/monitoring/netwatch.sh" /usr/local/sbin/ubrouter-netwatch.sh
  cat >/etc/systemd/system/ubrouter-netwatch.service <<'EOF'
[Unit]
Description=UBrouter netwatch (ping + optional Telegram)
After=network-online.target
Wants=network-online.target
[Service]
Type=oneshot
ExecStart=/usr/local/sbin/ubrouter-netwatch.sh
EOF
  cat >/etc/systemd/system/ubrouter-netwatch.timer <<EOF
[Unit]
Description=UBrouter netwatch timer
[Timer]
OnBootSec=45s
OnUnitActiveSec=${interval}s
AccuracySec=1s
Unit=ubrouter-netwatch.service
[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now ubrouter-netwatch.timer
  info "monitoring: netwatch.timer OK"
else
  systemctl disable --now ubrouter-netwatch.timer 2>/dev/null || true
fi

# --- vpn notify ---
if [[ "$vpn_on" -eq 1 ]]; then
  # Build watch list from vpn clients/servers + explicit monitoring.vpn_notify.interfaces
  python3 - "$UBROUTER_ANSWERS" <<'PY' >/etc/ubrouter/vpn-watch.conf
import json, sys
from pathlib import Path
try:
    import yaml
    ans = yaml.safe_load(Path(sys.argv[1]).read_text(encoding="utf-8")) or {}
except Exception:
    ans = {}
print("# iface|label|type — generated by UBrouter")
seen = set()
mon = ((ans.get("monitoring") or {}).get("vpn_notify") or {})
events = mon.get("events") or ["ikev2", "gre", "eoip", "wireguard", "openvpn"]
if isinstance(events, str):
    events = [x.strip() for x in events.split(",") if x.strip()]
for e in mon.get("interfaces") or []:
    if isinstance(e, dict):
        ifc, lab, typ = e.get("iface") or e.get("name"), e.get("label"), e.get("type") or "tunnel"
    else:
        ifc, lab, typ = str(e), str(e), "tunnel"
    if ifc and ifc not in seen:
        seen.add(ifc)
        print(f"{ifc}|{lab or ifc}|{typ}")
vpn = ans.get("vpn") or {}
for c in vpn.get("clients") or []:
    t = (c.get("type") or "").lower()
    if t == "ikev2":
        continue  # handled by updown hook
    if t not in events and t not in ("gre", "eoip", "wireguard", "openvpn", "ipip"):
        continue
    name = c.get("name") or t
    if t == "wireguard":
        ifc = name
    elif t == "openvpn":
        safe = "".join(ch if ch.isalnum() else "" for ch in str(name))[:8] or "ovpn"
        ifc = f"ovpn{safe}"[:15]
    else:
        ifc = name
    if ifc not in seen:
        seen.add(ifc)
        print(f"{ifc}|{name}|{t}")
for s in vpn.get("servers") or []:
    t = (s.get("type") or "").lower()
    if t == "wireguard":
        name = s.get("name") or "wg-server"
        if name not in seen:
            seen.add(name)
            print(f"{name}|{name}|wireguard")
    elif t == "openvpn" and ("openvpn" in events or True):
        name = s.get("name") or "ovpn-server"
        safe = "".join(ch if ch.isalnum() else "" for ch in str(name))[:8] or "ovpn"
        ifc = f"ovpn{safe}"[:15]
        if ifc not in seen:
            seen.add(ifc)
            print(f"{ifc}|{name}|openvpn")
PY
  chmod 0644 /etc/ubrouter/vpn-watch.conf

  cat >/etc/systemd/system/ubrouter-vpn-watch.service <<'EOF'
[Unit]
Description=UBrouter VPN tunnel watch (Telegram)
After=network-online.target
Wants=network-online.target
[Service]
Type=oneshot
ExecStart=/usr/local/sbin/ubrouter-vpn-watch.sh
EOF
  cat >/etc/systemd/system/ubrouter-vpn-watch.timer <<'EOF'
[Unit]
Description=UBrouter VPN tunnel watch timer
[Timer]
OnBootSec=60s
OnUnitActiveSec=15s
AccuracySec=2s
Unit=ubrouter-vpn-watch.service
[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now ubrouter-vpn-watch.timer
  info "monitoring: vpn-watch.timer OK; IKEv2 updown → /usr/local/sbin/ubrouter-vpn-updown-ikev2.sh"
  warn "Telegram API часто недоступен без bypass/VPN — иначе только syslog"
else
  systemctl disable --now ubrouter-vpn-watch.timer 2>/dev/null || true
fi

if [[ "$tg_en" -eq 1 ]]; then
  cur_token="$(grep -E '^TELEGRAM_BOT_TOKEN=' /etc/ubrouter/netwatch.env | cut -d= -f2-)"
  if [[ -z "$cur_token" || "$cur_token" == "CHANGE_ME" ]]; then
    warn "monitoring: Telegram без token — задайте monitoring.telegram в answers.local.yaml"
  fi
fi

info "monitoring: done"
