#!/usr/bin/env bash
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

if ! ans_true services.dnsmasq; then
  info "dns-dhcp: skip (dnsmasq off) — cleanup"
  systemctl disable --now dnsmasq 2>/dev/null || true
  # keep last conf as .ubrouter-disabled for rollback/history; remove active marker
  if [[ -f /etc/dnsmasq.conf ]] && grep -q 'Generated by UBrouter' /etc/dnsmasq.conf 2>/dev/null; then
    mv -f /etc/dnsmasq.conf /etc/dnsmasq.conf.ubrouter-disabled 2>/dev/null || true
  fi
  rm -f /etc/systemd/system/dnsmasq.service.d/ubrouter.conf 2>/dev/null || true
  systemctl daemon-reload 2>/dev/null || true
  if ans_true services.firewall || ans_true services.nat; then
    warn "dns-dhcp: dnsmasq выключен — гасим DNSStubListener (LAN :53 на роутере не будет)"
    if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
      mkdir -p /etc/systemd/resolved.conf.d
      cat >/etc/systemd/resolved.conf.d/ubrouter.conf <<'EOF'
[Resolve]
DNSStubListener=no
EOF
      systemctl restart systemd-resolved 2>/dev/null || true
    fi
  fi
  exit 0
fi

bash "$ROOT/scripts/modules/dns-dhcp/plan.sh"
WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"

# Disable systemd-resolved stub conflict on port 53 if active
if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
  if [[ -f /etc/systemd/resolved.conf ]]; then
    mkdir -p /etc/systemd/resolved.conf.d
    cat >/etc/systemd/resolved.conf.d/ubrouter.conf <<'EOF'
[Resolve]
DNSStubListener=no
EOF
    systemctl restart systemd-resolved 2>/dev/null || true
  fi
fi

install -m 0644 "$WORKDIR/dns-dhcp/dnsmasq.conf" /etc/dnsmasq.conf
mkdir -p /etc/dnsmasq.d
if ! grep -qE '^conf-dir=/etc/dnsmasq\.d' /etc/dnsmasq.conf; then
  echo 'conf-dir=/etc/dnsmasq.d/,*.conf' >>/etc/dnsmasq.conf
fi

dnsmasq --test

mkdir -p /etc/systemd/system/dnsmasq.service.d
cat >/etc/systemd/system/dnsmasq.service.d/ubrouter.conf <<'EOF'
[Unit]
After=network-online.target
Wants=network-online.target

[Service]
Restart=on-failure
RestartSec=3
EOF
systemctl daemon-reload
systemctl enable dnsmasq >/dev/null 2>&1 || true
systemctl restart dnsmasq
info "dns-dhcp: apply OK"
