#!/usr/bin/env bash
# Module: dns-dhcp — dnsmasq DNS+DHCP on LAN (+ DHCP tags / hosts)
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

if ! ans_true services.dnsmasq; then
  info "dns-dhcp: services.dnsmasq=false — skip"
  exit 0
fi

lan_if="$(ans_get lan.interface)"
if ans_true interfaces.bridge.enabled; then
  lan_if="$(ans_get interfaces.bridge.name)"
  [[ -n "$lan_if" ]] || lan_if=br-lan
fi
wan_if="$(ans_get wan.interface)"
cidr="$(ans_get lan.cidr)"
lan_ip="$(cidr_addr "$cidr")"
domain="$(ans_get lan.domain)"
[[ -n "$domain" ]] || domain=lan
dhcp_en=true
ans_true lan.dhcp.enabled || dhcp_en=false
pool_s="$(ans_get lan.dhcp.pool_start)"
pool_e="$(ans_get lan.dhcp.pool_end)"
lease="$(ans_get lan.dhcp.lease)"
[[ -n "$lease" ]] || lease=12h
up_json="$(ans_get_json dns.upstream)"
tags_json="$(ans_get_json lan.dhcp.tags 2>/dev/null || echo '[]')"
hosts_json="$(ans_get_json lan.dhcp.hosts 2>/dev/null || echo '[]')"

WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"
ensure_dir "$WORKDIR/dns-dhcp"

python3 - "$lan_if" "$wan_if" "$lan_ip" "$domain" "$dhcp_en" "$pool_s" "$pool_e" "$lease" \
  "$up_json" "$tags_json" "$hosts_json" \
  >"$WORKDIR/dns-dhcp/dnsmasq.conf" <<'PY'
import json, sys
(lan_if, wan_if, lan_ip, domain, dhcp_en, pool_s, pool_e, lease,
 up_json, tags_json, hosts_json) = sys.argv[1:]
ups = json.loads(up_json) if up_json and up_json != "null" else ["9.9.9.9", "1.1.1.1"]
tags = json.loads(tags_json) if tags_json and tags_json != "null" else []
hosts = json.loads(hosts_json) if hosts_json and hosts_json != "null" else []

def resolve_opt(vals):
    out = []
    for v in vals or []:
        if str(v).lower() == "router":
            out.append(lan_ip)
        else:
            out.append(str(v))
    return out

lines = [
    "# Generated by UBrouter",
    "domain-needed",
    "bogus-priv",
    "no-resolv",
    f"interface={lan_if}",
    f"except-interface={wan_if}",
    "bind-dynamic",
    f"listen-address={lan_ip}",
    f"domain={domain}",
    "expand-hosts",
    "cache-size=1000",
]
for u in ups:
    lines.append(f"server={u}")
if dhcp_en == "true":
    lines += [
        f"dhcp-range={pool_s},{pool_e},{lease}",
        f"dhcp-option=option:router,{lan_ip}",
        f"dhcp-option=option:dns-server,{lan_ip}",
        f"dhcp-option=option:ntp-server,{lan_ip}",
        "dhcp-authoritative",
    ]
    for t in tags:
        name = t.get("name") or ""
        if not name:
            continue
        dns = resolve_opt(t.get("dns") or ["router"])
        if dns:
            lines.append(f"dhcp-option=tag:{name},option:dns-server," + ",".join(dns))
        ntp = t.get("ntp")
        if ntp is not None:
            ntp_r = resolve_opt(ntp)
            if ntp_r:
                lines.append(f"dhcp-option=tag:{name},option:ntp-server," + ",".join(ntp_r))
            else:
                # empty = do not push NTP
                lines.append(f"# tag:{name} ntp off")
    for h in hosts:
        mac = (h.get("mac") or "").strip()
        if not mac:
            continue
        parts = [mac]
        tag = h.get("tag")
        if tag:
            parts.append(f"set:{tag}")
        ip = h.get("ip")
        if ip:
            parts.append(ip)
        hn = h.get("hostname")
        if hn:
            parts.append(hn)
        lines.append("dhcp-host=" + ",".join(parts))
print("\n".join(lines) + "\n")
PY

info "dns-dhcp: plan → workdir (tags/hosts included)"
