#!/usr/bin/env bash
# Module: ospf — optional FRR OSPFv2
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

en="$(ans_get routing.ospf.enabled 2>/dev/null || true)"
if [[ "$en" != "true" && "$en" != "1" && "$en" != "yes" ]]; then
  info "ospf: выключен — skip"
  if systemctl list-unit-files frr.service >/dev/null 2>&1; then
    systemctl disable --now frr 2>/dev/null || true
  fi
  exit 0
fi

export DEBIAN_FRONTEND=noninteractive
apt-get install -y -qq frr frr-pythontools >/dev/null || die "не удалось установить frr"

rid="$(ans_get routing.ospf.router_id 2>/dev/null || true)"
[[ -n "$rid" ]] || rid="$(ans_get lan.cidr | cut -d/ -f1)"
[[ -n "$rid" ]] || rid="10.0.0.1"
nets_json="$(ans_get_json routing.ospf.networks 2>/dev/null || echo '[]')"
passive_json="$(ans_get_json routing.ospf.passive_interfaces 2>/dev/null || echo '[]')"
redistribute="$(ans_get routing.ospf.redistribute_connected 2>/dev/null || echo true)"

# enable ospfd in daemons
if [[ -f /etc/frr/daemons ]]; then
  sed -i 's/^ospfd=.*/ospfd=yes/' /etc/frr/daemons
  sed -i 's/^zebra=.*/zebra=yes/' /etc/frr/daemons
fi

python3 - "$rid" "$nets_json" "$passive_json" "$redistribute" <<'PY' >/etc/frr/frr.conf
import json, sys
rid, nets_json, passive_json, redist = sys.argv[1:5]
nets = json.loads(nets_json or "[]") or []
passive = json.loads(passive_json or "[]") or []
lines = [
    "! Generated by UBrouter ospf",
    "frr version 8",
    "frr defaults traditional",
    "hostname ubrouter",
    "log syslog informational",
    "!",
    "router ospf",
    f" ospf router-id {rid}",
]
if redist in ("true", "1", "yes"):
    lines.append(" redistribute connected")
for p in passive:
    if p:
        lines.append(f" passive-interface {p}")
for n in nets:
    if isinstance(n, dict):
        prefix = n.get("prefix") or n.get("network")
        area = n.get("area") or "0.0.0.0"
    else:
        prefix, area = str(n), "0.0.0.0"
    if prefix:
        lines.append(f" network {prefix} area {area}")
lines += ["!", "line vty", "!"]
print("\n".join(lines) + "\n")
PY
chown frr:frr /etc/frr/frr.conf 2>/dev/null || true
chmod 0640 /etc/frr/frr.conf

systemctl enable frr
systemctl restart frr || warn "frr restart failed — journalctl -u frr"
info "ospf: FRR ospfd OK router-id=$rid"
