#!/usr/bin/env bash
# Reload CIDR/domain lists into nft set + dnsmasq nftset (generic, no bundled lists).
set -euo pipefail
ANSWERS="${UBROUTER_ANSWERS:-/etc/ubrouter/answers.yaml}"
YAML_GET="${UBROUTER_YAML_GET:-/usr/local/lib/ubrouter/yaml_answers.py}"
[[ -f "$YAML_GET" ]] || YAML_GET="$(dirname "$0")/yaml_answers.py"

enabled="$(python3 "$YAML_GET" get "$ANSWERS" bypass.enabled 2>/dev/null || echo false)"
[[ "$enabled" == "true" ]] || { echo "bypass disabled"; exit 0; }

mark="$(python3 "$YAML_GET" get "$ANSWERS" bypass.fwmark 2>/dev/null || echo 0x2)"
[[ -n "$mark" && "$mark" != "null" ]] || mark=0x2
table="$(python3 "$YAML_GET" get "$ANSWERS" bypass.table 2>/dev/null || echo 200)"
[[ -n "$table" && "$table" != "null" ]] || table=200
target="$(python3 "$YAML_GET" get "$ANSWERS" bypass.target 2>/dev/null || true)"
cidrs_json="$(python3 "$YAML_GET" get-json "$ANSWERS" bypass.cidr_files 2>/dev/null || echo '[]')"
domains_json="$(python3 "$YAML_GET" get-json "$ANSWERS" bypass.domain_files 2>/dev/null || echo '[]')"

nft list table inet ubrouter_bypass >/dev/null 2>&1 || {
  nft -f - <<'EOF'
table inet ubrouter_bypass {
  set bypass_dst {
    type ipv4_addr
    flags interval
    auto-merge
  }
}
EOF
}

nft flush set inet ubrouter_bypass bypass_dst 2>/dev/null || true

python3 - "$cidrs_json" <<'PY'
import json, re, subprocess, sys
from pathlib import Path

paths = json.loads(sys.argv[1] or "[]") or []
if isinstance(paths, str):
    paths = [paths]
cidrs = []
for p in paths:
    path = Path(p)
    files = sorted(path.glob("*")) if path.is_dir() else ([path] if path.is_file() else [])
    for f in files:
        if f.name.upper() == "README":
            continue
        for line in f.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            if re.match(r"^\d+\.\d+\.\d+\.\d+(\/\d+)?$", line):
                if "/" not in line:
                    line += "/32"
                cidrs.append(line)
for c in sorted(set(cidrs)):
    subprocess.call(["nft", "add", "element", "inet", "ubrouter_bypass", "bypass_dst", "{", c, "}"])
print(f"bypass cidrs loaded: {len(set(cidrs))}")
PY

mkdir -p /etc/dnsmasq.d
python3 - "$domains_json" <<'PY'
import json, sys
from pathlib import Path

paths = json.loads(sys.argv[1] or "[]") or []
if isinstance(paths, str):
    paths = [paths]
domains = []
for p in paths:
    path = Path(p)
    files = sorted(path.glob("*")) if path.is_dir() else ([path] if path.is_file() else [])
    for f in files:
        if f.name.upper() == "README":
            continue
        for line in f.read_text(encoding="utf-8", errors="ignore").splitlines():
            line = line.split("#", 1)[0].strip().lower()
            if not line or " " in line:
                continue
            if line.startswith("*."):
                line = line[2:]
            domains.append(line)
out = Path("/etc/dnsmasq.d/zz-ubrouter-bypass.conf")
lines = ["# Generated by UBrouter bypass-policy"]
for d in sorted(set(domains)):
    lines.append(f"nftset=/{d}/4#inet#ubrouter_bypass#bypass_dst")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"bypass domains: {len(set(domains))} → {out}")
PY

systemctl try-reload-or-restart dnsmasq 2>/dev/null || true

ip rule del fwmark "$mark" lookup "$table" 2>/dev/null || true
ip rule add fwmark "$mark" lookup "$table" priority 100

if [[ -n "$target" && "$target" != "null" ]]; then
  if ip link show "$target" >/dev/null 2>&1; then
    ip route replace default dev "$target" table "$table" 2>/dev/null \
      || ip route replace default dev "$target" table "$table" metric 10
    echo "bypass table $table default via $target"
  else
    echo "WARN: bypass target $target not up" >&2
  fi
fi

echo "bypass-reload OK"
