!/usr/bin/env bash
# OpenVPN: client (config_file) + server (PKI + issue .ovpn)
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

WORKDIR="${UBROUTER_WORKDIR:-/var/lib/ubrouter/work}"
clients_json="[]"
servers_json="[]"
[[ -f "$WORKDIR/vpn/clients.json" ]] && clients_json="$(cat "$WORKDIR/vpn/clients.json")"
[[ -f "$WORKDIR/vpn/servers.json" ]] && servers_json="$(cat "$WORKDIR/vpn/servers.json")"
if [[ "$clients_json" == "[]" && "$servers_json" == "[]" ]]; then
  clients_json="$(ans_get_json vpn.clients)"
  servers_json="$(ans_get_json vpn.servers)"
fi

ensure_dir /etc/openvpn/client
ensure_dir /etc/openvpn/server
ensure_dir /var/lib/ubrouter/openvpn-pki
ensure_dir /var/lib/ubrouter/vpn
ensure_dir /root/ubrouter-vpn-clients

# --- clients + orphan reconcile ---
python3 - "$clients_json" <<'PY'
import json, shutil, subprocess, sys
from pathlib import Path

clients = [c for c in (json.loads(sys.argv[1] or "[]") or []) if c.get("type") == "openvpn"]
state = Path("/var/lib/ubrouter/vpn/managed-openvpn-client.list")
prev = state.read_text(encoding="utf-8").split() if state.is_file() else []
desired = [c.get("name") or "client" for c in clients]
keep = set(desired)

def disable_client(name: str):
    subprocess.call(
        ["systemctl", "disable", "--now", f"openvpn-client@{name}"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    conf = Path(f"/etc/openvpn/client/{name}.conf")
    if conf.is_file():
        conf.rename(str(conf) + ".ubrouter-disabled")

for name in prev:
    if name and name not in keep:
        print(f"--> openvpn: remove orphan client {name}")
        disable_client(name)

for c in clients:
    name = c.get("name") or "client"
    cfg = c.get("config_file")
    if not cfg or not Path(cfg).is_file():
        print(f"WARN: openvpn {name}: нет config_file — skip", file=sys.stderr)
        continue
    dst = Path(f"/etc/openvpn/client/{name}.conf")
    shutil.copy2(cfg, dst)
    text = dst.read_text(encoding="utf-8", errors="ignore")
    if "Generated by UBrouter" not in text:
        dst.write_text("# Generated by UBrouter (client)\n" + text, encoding="utf-8")
    dst.chmod(0o600)
    subprocess.check_call(["systemctl", "enable", f"openvpn-client@{name}"])
    subprocess.call(["systemctl", "restart", f"openvpn-client@{name}"])
    print(f"--> openvpn: client {name}")

state.write_text("\n".join(desired) + ("\n" if desired else ""), encoding="utf-8")
if not clients:
    print("--> openvpn: no clients (cleanup orphans done)")
PY

# --- servers ---
python3 - "$servers_json" "$ROOT" <<'PY'
import json, os, subprocess, sys, textwrap
from pathlib import Path

servers = [s for s in (json.loads(sys.argv[1] or "[]") or []) if s.get("type") == "openvpn"]
root = sys.argv[2]
state = Path("/var/lib/ubrouter/vpn/managed-openvpn-server.list")
prev = state.read_text(encoding="utf-8").split() if state.is_file() else []
desired = [s.get("name") or "ovpn-server" for s in servers]
keep = set(desired)

def disable_server(name: str):
    subprocess.call(
        ["systemctl", "disable", "--now", f"openvpn-server@{name}"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    conf = Path(f"/etc/openvpn/server/{name}.conf")
    if conf.is_file() and "Generated by UBrouter" in conf.read_text(encoding="utf-8", errors="ignore"):
        conf.rename(str(conf) + ".ubrouter-disabled")

for name in prev:
    if name and name not in keep:
        print(f"--> openvpn: remove orphan server {name}")
        disable_server(name)

state.write_text("\n".join(desired) + ("\n" if desired else ""), encoding="utf-8")
if not servers:
    print("--> openvpn: no servers")
    raise SystemExit(0)

PKI = Path("/var/lib/ubrouter/openvpn-pki")
CLIENTS = Path("/root/ubrouter-vpn-clients")
PKI.mkdir(parents=True, exist_ok=True)
(CLIENTS).mkdir(parents=True, exist_ok=True)

def run(cmd, **kw):
    subprocess.check_call(cmd, **kw)

def ensure_ca():
    ca_key = PKI / "ca.key"
    ca_crt = PKI / "ca.crt"
    if ca_key.is_file() and ca_crt.is_file():
        return
    run(["openssl", "genrsa", "-out", str(ca_key), "2048"])
    ca_key.chmod(0o600)
    run([
        "openssl", "req", "-x509", "-new", "-nodes",
        "-key", str(ca_key), "-sha256", "-days", "3650",
        "-out", str(ca_crt),
        "-subj", "/CN=UBrouter-OpenVPN-CA",
    ])
    print("--> openvpn: CA created")

def issue_server(name: str, listen: int, proto: str, network: str, dns: str):
    ensure_ca()
    skey = PKI / f"{name}.key"
    scsr = PKI / f"{name}.csr"
    scrt = PKI / f"{name}.crt"
    if not skey.is_file():
        run(["openssl", "genrsa", "-out", str(skey), "2048"])
        skey.chmod(0o600)
        run([
            "openssl", "req", "-new", "-key", str(skey), "-out", str(scsr),
            "-subj", f"/CN={name}",
        ])
        run([
            "openssl", "x509", "-req", "-in", str(scsr),
            "-CA", str(PKI / "ca.crt"), "-CAkey", str(PKI / "ca.key"),
            "-CAcreateserial", "-out", str(scrt), "-days", "825", "-sha256",
        ])
    dh = PKI / "dh.pem"
    if not dh.is_file():
        run(["openssl", "dhparam", "-out", str(dh), "2048"])
    ta = PKI / "ta.key"
    if not ta.is_file():
        run(["openvpn", "--genkey", "secret", str(ta)])
        ta.chmod(0o600)

    conf = Path(f"/etc/openvpn/server/{name}.conf")
    # stable iface name for vpn-watch / nft (max 15 chars)
    safe = "".join(ch if ch.isalnum() else "" for ch in str(name))[:8] or "ovpn"
    devname = f"ovpn{safe}"[:15]
    conf.write_text(textwrap.dedent(f"""\
        # Generated by UBrouter
        port {listen}
        proto {proto}
        dev-type tun
        dev {devname}
        ca {PKI / "ca.crt"}
        cert {scrt}
        key {skey}
        dh {dh}
        tls-auth {ta} 0
        server {network.split("/")[0].rsplit(".", 1)[0]}.0 255.255.255.0
        topology subnet
        push "redirect-gateway def1 bypass-dhcp"
        push "dhcp-option DNS {dns}"
        keepalive 10 120
        cipher AES-256-GCM
        data-ciphers AES-256-GCM:AES-128-GCM
        user nobody
        group nogroup
        persist-key
        persist-tun
        status /var/log/openvpn-{name}-status.log
        verb 3
        explicit-exit-notify 1
        """), encoding="utf-8")
    # Fix server directive from CIDR if provided
    # network like 10.8.0.0/24
    conf.chmod(0o600)
    # rewrite server line properly
    net = network if "/" in network else "10.8.0.0/24"
    ip, pfx = net.split("/")
    mask = {
        "24": "255.255.255.0",
        "16": "255.255.0.0",
        "8": "255.0.0.0",
    }.get(pfx, "255.255.255.0")
    text = conf.read_text(encoding="utf-8")
    lines = []
    for ln in text.splitlines():
        if ln.startswith("server "):
            lines.append(f"server {ip} {mask}")
        else:
            lines.append(ln)
    conf.write_text("\n".join(lines) + "\n", encoding="utf-8")

    run(["systemctl", "enable", f"openvpn-server@{name}"])
    subprocess.call(["systemctl", "restart", f"openvpn-server@{name}"])
    print(f"--> openvpn: server {name} listen {listen}/{proto} dev={devname}")

    # open firewall
    subprocess.call(
        f'nft list table inet filter >/dev/null 2>&1 && '
        f'nft add rule inet filter input udp dport {listen} accept 2>/dev/null || true',
        shell=True,
    )
    if proto == "tcp":
        subprocess.call(
            f'nft add rule inet filter input tcp dport {listen} accept 2>/dev/null || true',
            shell=True,
        )

def issue_client(server_name: str, client_name: str, remote: str, listen: int, proto: str):
    ensure_ca()
    ckey = PKI / f"client-{client_name}.key"
    ccsr = PKI / f"client-{client_name}.csr"
    ccrt = PKI / f"client-{client_name}.crt"
    if not ckey.is_file():
        run(["openssl", "genrsa", "-out", str(ckey), "2048"])
        ckey.chmod(0o600)
        run([
            "openssl", "req", "-new", "-key", str(ckey), "-out", str(ccsr),
            "-subj", f"/CN={client_name}",
        ])
        run([
            "openssl", "x509", "-req", "-in", str(ccsr),
            "-CA", str(PKI / "ca.crt"), "-CAkey", str(PKI / "ca.key"),
            "-CAcreateserial", "-out", str(ccrt), "-days", "825", "-sha256",
        ])
    ca = (PKI / "ca.crt").read_text(encoding="utf-8").strip()
    cert = ccrt.read_text(encoding="utf-8").strip()
    key = ckey.read_text(encoding="utf-8").strip()
    ta = (PKI / "ta.key").read_text(encoding="utf-8").strip()
    ovpn = CLIENTS / f"{client_name}.ovpn"
    ovpn.write_text(textwrap.dedent(f"""\
        client
        dev tun
        proto {proto}
        remote {remote} {listen}
        resolv-retry infinite
        nobind
        persist-key
        persist-tun
        remote-cert-tls server
        cipher AES-256-GCM
        data-ciphers AES-256-GCM:AES-128-GCM
        verb 3
        key-direction 1
        <ca>
        {ca}
        </ca>
        <cert>
        {cert}
        </cert>
        <key>
        {key}
        </key>
        <tls-auth>
        {ta}
        </tls-auth>
        """), encoding="utf-8")
    ovpn.chmod(0o600)
    howto = CLIENTS / f"{client_name}.howto.txt"
    howto.write_text(
        f"OpenVPN client profile for {client_name}\n"
        f"Import {ovpn} into OpenVPN Connect / NetworkManager.\n"
        f"Server: {remote}:{listen}/{proto}\n",
        encoding="utf-8",
    )
    print(f"--> openvpn: client profile {ovpn}")

for s in servers:
    name = s.get("name") or "ovpn-server"
    listen = int(s.get("listen") or 1194)
    proto = (s.get("proto") or "udp").lower()
    network = s.get("network") or "10.8.0.0/24"
    dns = (s.get("dns") or ["10.0.0.1"])
    if isinstance(dns, list):
        dns = dns[0] if dns else "10.0.0.1"
    remote = s.get("public_host") or s.get("id") or "auto"
    if remote == "auto":
        # best-effort: first global IPv4
        try:
            out = subprocess.check_output(
                ["bash", "-c", "ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i==\"src\"){print $(i+1); exit}}'"],
                text=True,
            ).strip()
            remote = out or "CHANGE_ME_PUBLIC_IP"
        except Exception:
            remote = "CHANGE_ME_PUBLIC_IP"
    issue_server(name, listen, proto, network, str(dns))
    for cn in s.get("clients") or []:
        if isinstance(cn, dict):
            cn = cn.get("name") or ""
        if not cn:
            continue
        issue_client(name, str(cn), remote, listen, proto)
PY

info "openvpn: done"
