#!/usr/bin/env bash
# Module: igmpproxy — IPTV multicast proxy
set -euo pipefail
ROOT="${UBROUTER_ROOT:?}"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/common.sh"
# shellcheck source=/dev/null
source "$ROOT/scripts/lib/answers.sh"
ans_require
need_root

if ! ans_true igmpproxy.enabled && ! ans_true services.igmpproxy; then
  info "igmpproxy: disabled — cleanup"
  systemctl disable --now igmpproxy 2>/dev/null || true
  if [[ -f /etc/igmpproxy.conf ]] && grep -q 'Generated by UBrouter' /etc/igmpproxy.conf 2>/dev/null; then
    mv -f /etc/igmpproxy.conf /etc/igmpproxy.conf.ubrouter-disabled 2>/dev/null || true
  fi
  exit 0
fi

up="$(ans_get igmpproxy.upstream)"
down="$(ans_get igmpproxy.downstream)"
[[ -n "$up" && "$up" != "null" ]] || up="$(ans_get wan.interface)"
[[ -n "$down" && "$down" != "null" ]] || {
  if ans_true interfaces.bridge.enabled; then
    down="$(ans_get interfaces.bridge.name)"
  else
    down="$(ans_get lan.interface)"
  fi
}
ql=true
ans_true igmpproxy.quickleave || ql=false
altnet="$(ans_get igmpproxy.altnet)"

{
  echo "# Generated by UBrouter"
  [[ "$ql" == "true" ]] && echo "quickleave"
  echo
  echo "phyint $up upstream  ratelimit 0  threshold 1"
  if [[ -n "$altnet" && "$altnet" != "null" ]]; then
    echo "  altnet $altnet"
  fi
  echo
  echo "phyint $down downstream  ratelimit 0  threshold 1"
} >/etc/igmpproxy.conf

# nft: allow IGMP / multicast forward (best-effort append)
nft list table inet filter >/dev/null 2>&1 && {
  nft add rule inet filter input iifname "$up" ip protocol igmp accept 2>/dev/null || true
  nft add rule inet filter input iifname "$down" ip protocol igmp accept 2>/dev/null || true
  nft add rule inet filter forward iifname "$up" oifname "$down" accept 2>/dev/null || true
  nft add rule inet filter forward iifname "$down" oifname "$up" accept 2>/dev/null || true
} || true

sysctl -w net.ipv4.conf.all.mc_forwarding=1 >/dev/null 2>&1 || true
sysctl -w "net.ipv4.conf.${up}.mc_forwarding=1" >/dev/null 2>&1 || true

systemctl enable igmpproxy >/dev/null 2>&1 || true
systemctl restart igmpproxy || warn "igmpproxy start failed"
info "igmpproxy: upstream=$up downstream=$down"
